Created summary component
MichaelDysart/SYSC4806_Project pull request #76
Opened 2020-04-01 01:31 UTC by MichaelDysart

Created summary of number question type

2020-04-01 02:18 UTC, rinadina approved these changes
Looks fine.

2020-04-01 05:38 UTC, JacksonSchoe approved these changes
Looks good Michael

2020-04-02 00:35 UTC, TaylorAbraham requested changes
Looks great. Nice job adding the histogram. Just remove a couple console.logs

2020-04-02 00:35 UTC, TaylorAbraham commented on src/main/js/App.js
> +        console.log(`${webUrl}retrieveSurvey?id=${userSurveyId}`);
Lingering console.log

2020-04-02 00:35 UTC, TaylorAbraham commented on src/main/js/Summary.js
> +    console.log(props);
And here

2020-04-02 01:00 UTC, rinadina approved these changes

2020-04-02 01:27 UTC, rinadina commented on src/main/js/Summary.js
> +                                <div>{`Question ${i + 1} - Numerical`}</div>
Is it suppose to say Numerical for open ended ?

2020-04-02 11:45 UTC, merged