Fixed the console
MichaelDysart/SYSC4806_Project pull request #78
Opened 2020-04-01 05:41 UTC by JacksonSchoe

Taylor please look into my implementation of hiding of the console and production, and look into testing it if possible because I wasn't sure how to test if it was hidden in production.

2020-04-01 05:53 UTC, JacksonSchoe commented
![image](https://user-images.githubusercontent.com/19473324/78103702-92f79880-73bb-11ea-9235-9cb3a46eb106.png)

2020-04-01 12:34 UTC, TaylorAbraham requested changes

2020-04-01 12:34 UTC, TaylorAbraham commented on src/main/js/App.js
> +                    {process.env.NODE_ENV !== 'production' &&
Good use of &&. Once we merge this, we should make sure to check that this does NOT appear on heroku.

2020-04-01 12:34 UTC, TaylorAbraham commented on src/main/js/App.js
> -                    <textarea readOnly value={consoleText} class="console"></textarea>
This used to have a class, we should add `className="console"` to the redone component.

2020-04-02 00:48 UTC, TaylorAbraham approved these changes
You fixed my comment, so looks all good now!

2020-04-02 00:50 UTC, merged